version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.test
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    env_file:
      - .env.test

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ management UI
