# Use a base image for Node.js
FROM node:16

# Set working directory
WORKDIR /usr/src/app

# Copy application code
COPY . .

# Install application dependencies
RUN npm install

# Expose the application port
EXPOSE 5000

# Start the Node.js application
CMD ["node", "index.js"]
